const express = require('express');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const Area = require('../models/Area');
const Manager = require('../models/Manager');
const Shop = require('../models/Shop');
const User = require('../models/User');
const Module = require('../models/Module');
const router = express.Router();

// ========== MIDDLEWARE: Manager Token Verify ==========
const verifyManagerToken = async (req, res, next) => {
    try {
        const token = req.headers.authorization?.split(' ')[1];
        if (!token) {
            return res.status(401).json({ error: 'No token provided' });
        }

        const manager = await Manager.findOne({ loginToken: token, status: true });
        if (!manager) {
            return res.status(401).json({ error: 'Invalid or expired token' });
        }

        req.manager = manager;
        next();
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

// ========== ADMIN ROUTES ==========

// 1. Get All Managers - manager.html ke liye
router.get('/managers', async (req, res) => {
    try {
        const managers = await Manager.find().sort({ createdAt: -1 });
        res.json(managers);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 2. Get Single Manager Detail
router.get('/managers/:id', async (req, res) => {
    try {
        const manager = await Manager.findById(req.params.id);
        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }
        res.json(manager);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 3. Auto Create Manager - Manual sync ke liye bhi
router.post('/admin/auto-create-manager', async (req, res) => {
    try {
        const { areaCode } = req.body;

        if (!areaCode) {
            return res.status(400).json({ error: 'Area Code required' });
        }

        const existingManager = await Manager.findOne({ areaCode });
        if (existingManager) {
            return res.json({ success: true, manager: existingManager, message: 'Manager already exists' });
        }

        const area = await Area.findOne({ areaCode });
        if (!area) {
            return res.status(404).json({ error: 'Area not found' });
        }

        const loginToken = crypto.randomBytes(32).toString('hex');
        const tempPassword = 'Auto@' + Math.random().toString(36).substring(2, 8).toUpperCase();
        const hashedPassword = await bcrypt.hash(tempPassword, 10);

        const managerData = {
            name: `${area.areaName} Manager`,
            areaCode: area.areaCode,
            areaName: area.areaName,
            city: area.city,
            state: area.state,
            bucket: 'DEFAULT',
            managerCode: `${area.areaCode}-DEFAULT`,
            email: `${area.areaCode.toLowerCase()}@autogen.local`,
            phone: '0000000000',
            password: hashedPassword,
            serviceCharge: 5,
            status: true,
            moduleAccess: [],
            autoGenerated: true,
            loginToken: loginToken,
            tempPassword: tempPassword,
            centerLat: area.centerLat,
            centerLng: area.centerLng,
            radius: area.radius
        };

        const manager = new Manager(managerData);
        await manager.save();

        console.log(`✅ Auto Manager created for area: ${area.areaCode}`);
        res.status(201).json({
            success: true,
            manager,
            loginLink: `/area-manager.html?token=${loginToken}`,
            tempPassword: tempPassword
        });

    } catch (err) {
        console.error('Auto create manager error:', err);
        res.status(500).json({ error: err.message });
    }
});

// 4. Update Manager - General update
router.put('/managers/:id', async (req, res) => {
    try {
        const updateData = req.body;

        // Password update ho raha hai to hash karo
        if (updateData.password) {
            updateData.password = await bcrypt.hash(updateData.password, 10);
        }

        const manager = await Manager.findByIdAndUpdate(
            req.params.id,
            updateData,
            { new: true, runValidators: true }
        );

        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }

        res.json({ success: true, manager });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 5. Update Manager Modules - Service assign karne ke liye
router.put('/managers/:id/modules', async (req, res) => {
    try {
        const { moduleAccess } = req.body;

        if (!Array.isArray(moduleAccess)) {
            return res.status(400).json({ error: 'moduleAccess must be an array' });
        }

        const manager = await Manager.findByIdAndUpdate(
            req.params.id,
            { moduleAccess },
            { new: true }
        );

        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }

        res.json({ success: true, manager });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 6. Reset Manager Password
router.post('/managers/:id/reset-password', async (req, res) => {
    try {
        const manager = await Manager.findById(req.params.id);
        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }

        const newPassword = 'Auto@' + Math.random().toString(36).substring(2, 8).toUpperCase();
        const hashedPassword = await bcrypt.hash(newPassword, 10);
        const newToken = crypto.randomBytes(32).toString('hex');

        manager.password = hashedPassword;
        manager.loginToken = newToken;
        manager.tempPassword = newPassword;
        await manager.save();

        res.json({
            success: true,
            tempPassword: newPassword,
            loginLink: `/area-manager.html?token=${newToken}`
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 7. Delete Manager
router.delete('/managers/:id', async (req, res) => {
    try {
        const manager = await Manager.findById(req.params.id);
        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }

        const shopCount = await Shop.countDocuments({ managerId: manager._id });
        if (shopCount > 0) {
            return res.status(400).json({
                error: `Cannot delete! ${shopCount} shops are assigned to this manager.`
            });
        }

        await Manager.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Manager deleted successfully' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 8. Get All Modules - Service assign karte time dropdown ke liye
router.get('/modules', async (req, res) => {
    try {
        const modules = await Module.find({ status: true }).sort({ name: 1 });
        res.json({ modules });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ========== MANAGER ROUTES - Dashboard Ke Liye ==========

// 9. Manager Login
router.post('/area-manager/login', async (req, res) => {
    try {
        const { email, password } = req.body;

        const manager = await Manager.findOne({ email, status: true });
        if (!manager) {
            return res.status(401).json({ error: 'Invalid credentials' });
        }

        const isMatch = await bcrypt.compare(password, manager.password);
        if (!isMatch) {
            return res.status(401).json({ error: 'Invalid credentials' });
        }

        res.json({
            success: true,
            token: manager.loginToken,
            manager: {
                _id: manager._id,
                name: manager.name,
                email: manager.email,
                areaCode: manager.areaCode,
                areaName: manager.areaName,
                city: manager.city,
                bucket: manager.bucket,
                modules: manager.moduleAccess
            }
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 10. Manager Dashboard Data
router.get('/manager/dashboard', verifyManagerToken, async (req, res) => {
    try {
        const manager = req.manager;

        const [shops, categories, area, allShops] = await Promise.all([
            Shop.find({ managerId: manager._id }),
            Module.find({ id: { $in: manager.moduleAccess } }),
            Area.findOne({ areaCode: manager.areaCode }),
            Shop.find({}) // Overlap check ke liye sab shops
        ]);

        res.json({
            success: true,
            manager: {
                _id: manager._id,
                name: manager.name,
                areaCode: manager.areaCode,
                areaName: manager.areaName,
                city: manager.city,
                bucket: manager.bucket,
                managerCode: manager.managerCode,
                serviceCharge: manager.serviceCharge,
                modules: manager.moduleAccess,
                centerLat: area?.centerLat,
                centerLng: area?.centerLng,
                radius: area?.radius
            },
            shops,
            categories,
            area,
            stats: {
                totalShops: shops.length,
                activeShops: shops.filter(s => s.status).length
            }
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 11. Create Shop - Circle Overlap + Category Validation
router.post('/manager/shop', verifyManagerToken, async (req, res) => {
    try {
        const manager = req.manager;
        const { name, icon, moduleId, phone, address, lat, lng, range, banner } = req.body;

        // Validation 1: Category access check
        if (!manager.moduleAccess.includes(moduleId)) {
            return res.status(403).json({ error: 'You dont have access to this category' });
        }

        // Validation 2: Area circle check
        const area = await Area.findOne({ areaCode: manager.areaCode });
        if (!area) {
            return res.status(404).json({ error: 'Area not found' });
        }

        const distance = calculateDistance(lat, lng, area.centerLat, area.centerLng);

        if (distance > area.radius) {
            return res.status(400).json({
                error: `Shop location is ${distance.toFixed(1)}km away. Must be within ${area.radius}km`
            });
        }

        // Validation 3: Overlap check - Dusre area me paas to nahi
        const allAreas = await Area.find({ status: true, areaCode: { $ne: manager.areaCode } });
        for (const otherArea of allAreas) {
            const distToOther = calculateDistance(lat, lng, otherArea.centerLat, otherArea.centerLng);
            if (distToOther <= otherArea.radius && distToOther < distance) {
                return res.status(400).json({
                    error: `This location is closer to ${otherArea.areaName} (${distToOther.toFixed(1)}km)`
                });
            }
        }

        const shop = new Shop({
            name,
            icon: icon || '🏪',
            moduleId,
            phone,
            address,
            lat: parseFloat(lat),
            lng: parseFloat(lng),
            range: parseInt(range) || 5000,
            banner,
            areaCode: manager.areaCode,
            managerId: manager._id,
            city: manager.city,
            status: true,
            bannerStatus: 'pending'
        });

        await shop.save();
        res.status(201).json({ success: true, shop });

    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 12. Update Shop
router.put('/manager/shop/:id', verifyManagerToken, async (req, res) => {
    try {
        const manager = req.manager;
        const shop = await Shop.findOne({ _id: req.params.id, managerId: manager._id });

        if (!shop) {
            return res.status(404).json({ error: 'Shop not found or access denied' });
        }

        // Agar location change ho rahi hai to wapas validation
        if (req.body.lat && req.body.lng) {
            const area = await Area.findOne({ areaCode: manager.areaCode });
            const distance = calculateDistance(req.body.lat, req.body.lng, area.centerLat, area.centerLng);

            if (distance > area.radius) {
                return res.status(400).json({
                    error: `New location is ${distance.toFixed(1)}km away. Must be within ${area.radius}km`
                });
            }
        }

        Object.assign(shop, req.body);
        await shop.save();

        res.json({ success: true, shop });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 13. Delete Shop
router.delete('/manager/shop/:id', verifyManagerToken, async (req, res) => {
    try {
        const manager = req.manager;
        const shop = await Shop.findOneAndDelete({ _id: req.params.id, managerId: manager._id });

        if (!shop) {
            return res.status(404).json({ error: 'Shop not found or access denied' });
        }

        res.json({ success: true, message: 'Shop deleted' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// 14. Get Manager's Shops - Nearby logic ke sath
router.get('/manager/shops', verifyManagerToken, async (req, res) => {
    try {
        const manager = req.manager;
        const shops = await Shop.find({ managerId: manager._id }).sort({ createdAt: -1 });
        res.json({ success: true, shops });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ========== HELPER FUNCTION: Haversine Distance ==========
function calculateDistance(lat1, lon1, lat2, lon2) {
    const R = 6371; // Earth radius in km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a =
        Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
        Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c;
}

module.exports = router;