const express = require('express');
const router = express.Router();
const Area = require('../models/Area');
const Manager = require('../models/Manager');
const crypto = require('crypto');

router.get('/areas', async (req, res) => {
    try {
        const areas = await Area.find().sort({ createdAt: -1 });
        res.json(areas);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

router.post('/areas', async (req, res) => {
    try {
        const area = new Area(req.body);
        await area.save();

        const loginToken = crypto.randomBytes(32).toString('hex');
        const manager = new Manager({
            areaCode: area.areaCode,
            managerCode: area.areaCode + '-DEFAULT',
            name: area.areaName + ' Manager',
            email: `${area.areaCode.toLowerCase()}@autogen.local`,
            city: area.city,
            areaName: area.areaName,
            loginToken: loginToken,
            centerLat: area.centerLat,
            centerLng: area.centerLng,
            radius: area.radius,
            autoGenerated: true
        });
        await manager.save();

        res.json({ success: true, area, manager });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

router.put('/areas/:id', async (req, res) => {
    try {
        const area = await Area.findByIdAndUpdate(req.params.id, req.body, { new: true });
        res.json({ success: true, area });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

router.delete('/areas/:id', async (req, res) => {
    try {
        const area = await Area.findById(req.params.id);
        const managerCount = await Manager.countDocuments({ areaCode: area.areaCode });
        
        if (managerCount > 0) {
            return res.status(400).json({ error: 'Cannot delete. Managers exist in this area.' });
        }
        
        await Area.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

router.get('/managers', async (req, res) => {
    try {
        const managers = await Manager.find().sort({ createdAt: -1 });
        res.json(managers);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

router.get('/users', async (req, res) => res.json([]));
router.get('/shops', async (req, res) => res.json([]));
router.get('/products', async (req, res) => res.json([]));
router.get('/modules', async (req, res) => res.json({ modules: [] }));

module.exports = router;