const express = require('express');
const router = express.Router();
const Area = require('../models/Area');
const Manager = require('../models/Manager');
const Shop = require('../models/Shop');
const crypto = require('crypto');

// GET all areas
router.get('/areas', async (req, res) => {
    try {
        const areas = await Area.find().sort({ createdAt: -1 });
        res.json(areas);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// POST create area + auto create manager
router.post('/areas', async (req, res) => {
    try {
        const area = new Area(req.body);
        await area.save();

        const loginToken = crypto.randomBytes(32).toString('hex');
        const manager = new Manager({
            areaCode: area.areaCode,
            managerCode: area.areaCode + '-DEFAULT',
            name: req.body.managerName || area.areaName + ' Manager',
            email: req.body.managerEmail || `${area.areaCode.toLowerCase()}@autogen.local`,
            phone: req.body.managerPhone || req.body.phone || '',
            photo: req.body.managerPhoto || '', // ← PHOTO SUPPORT
            city: area.city,
            state: area.state,
            areaName: area.areaName,
            bucket: req.body.bucket || 'DEFAULT',
            loginToken: loginToken,
            centerLat: area.centerLat,
            centerLng: area.centerLng,
            radius: area.radius,
            status: true,
            autoGenerated: true,
            serviceCharge: req.body.serviceCharge || 0
        });
        await manager.save();

        res.json({ success: true, area, manager });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// PUT update area - Manager bhi update hoga
router.put('/areas/:id', async (req, res) => {
    try {
        const area = await Area.findByIdAndUpdate(req.params.id, req.body, { new: true });
        
        const updateFields = { 
            areaName: area.areaName,
            city: area.city,
            state: area.state,
            centerLat: area.centerLat,
            centerLng: area.centerLng,
            radius: area.radius,
            bucket: req.body.bucket || 'DEFAULT'
        };

        // Photo update support
        if (req.body.managerPhoto !== undefined) updateFields.photo = req.body.managerPhoto;
        if (req.body.managerName) updateFields.name = req.body.managerName;
        if (req.body.managerPhone) updateFields.phone = req.body.managerPhone;
        if (req.body.managerEmail) updateFields.email = req.body.managerEmail;
        
        await Manager.updateMany(
            { areaCode: area.areaCode },
            updateFields
        );
        
        res.json({ success: true, area });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// DELETE area
router.delete('/areas/:id', async (req, res) => {
    try {
        const area = await Area.findById(req.params.id);
        if (!area) {
            return res.status(404).json({ error: 'Area not found' });
        }
        
        const managerCount = await Manager.countDocuments({ areaCode: area.areaCode });
        if (managerCount > 0) {
            return res.status(400).json({ error: 'Cannot delete. Managers exist in this area.' });
        }
        
        await Area.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// GET all managers
router.get('/managers', async (req, res) => {
    try {
        const managers = await Manager.find().sort({ createdAt: -1 });
        res.json(managers);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// GET manager by token
router.get('/manager-by-token/:token', async (req, res) => {
    try {
        const manager = await Manager.findOne({ loginToken: req.params.token });
        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }
        res.json({ success: true, manager });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// PUT update manager by ID - Admin ke liye
router.put('/managers/:id', async (req, res) => {
    try {
        const manager = await Manager.findByIdAndUpdate(req.params.id, req.body, { new: true });
        if (!manager) {
            return res.status(404).json({ error: 'Manager not found' });
        }
        res.json({ success: true, manager });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// PUT update manager by managerCode - Manager dashboard se profile update ke liye ← NAYA
router.put('/managers/:managerCode', async (req, res) => {
    try {
        const { managerCode } = req.params;
        const { name, phone, email, photo } = req.body;
        
        const manager = await Manager.findOneAndUpdate(
            { managerCode },
            { $set: { name, phone, email, photo } },
            { new: true }
        );
        
        if (!manager) {
            return res.status(404).json({ success: false, error: 'Manager not found' });
        }
        
        res.json({ success: true, manager });
    } catch (err) {
        res.status(500).json({ success: false, error: err.message });
    }
});

// GET all shops
router.get('/shops', async (req, res) => {
    try {
        const shops = await Shop.find().sort({ createdAt: -1 });
        res.json(shops);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// POST create shop
router.post('/shops', async (req, res) => {
    try {
        const shopData = {
            ...req.body,
            location: {
                type: 'Point',
                coordinates: [req.body.lng, req.body.lat]
            }
        };
        delete shopData.lat;
        delete shopData.lng;
        
        const shop = new Shop(shopData);
        await shop.save();
        res.json({ success: true, shop });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// PUT update shop
router.put('/shops/:id', async (req, res) => {
    try {
        const updateData = { ...req.body };
        if (req.body.lat && req.body.lng) {
            updateData.location = {
                type: 'Point',
                coordinates: [req.body.lng, req.body.lat]
            };
            delete updateData.lat;
            delete updateData.lng;
        }
        const shop = await Shop.findByIdAndUpdate(req.params.id, updateData, { new: true });
        res.json({ success: true, shop });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
});

// DELETE shop
router.delete('/shops/:id', async (req, res) => {
    try {
        await Shop.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

router.get('/users', async (req, res) => res.json([]));
router.get('/products', async (req, res) => res.json([]));
router.get('/modules', async (req, res) => res.json({ modules: [] }));

module.exports = router;
