const mongoose = require('mongoose');

const managerSchema = new mongoose.Schema({
    areaCode: { 
        type: String, 
        required: true, 
        index: true 
    },
    managerCode: { 
        type: String, 
        required: true, 
        unique: true 
    },
    name: { 
        type: String, 
        required: true,
        trim: true
    },
    email: { 
        type: String, 
        required: true,
        lowercase: true,
        trim: true
    },
    phone: { 
        type: String,
        trim: true,
        default: ''
    },
    photo: { 
        type: String, 
        default: '',
        trim: true
    },
    city: { 
        type: String,
        trim: true
    },
    state: { 
        type: String,
        trim: true
    },
    areaName: { 
        type: String,
        trim: true
    },
    bucket: { 
        type: String, 
        default: 'DEFAULT',
        trim: true
    },
    loginToken: { 
        type: String, 
        required: true, 
        index: true,
        unique: true
    },
    status: { 
        type: Boolean, 
        default: true 
    },
    autoGenerated: { 
        type: Boolean, 
        default: true 
    },
    serviceCharge: { 
        type: Number, 
        default: 0 
    },
    moduleAccess: [{ 
        type: String 
    }],
    centerLat: { 
        type: Number 
    },
    centerLng: { 
        type: Number 
    },
    radius: { 
        type: Number 
    },
    maxShops: { 
        type: Number, 
        default: 10,
        min: 1
    },

    // ✅ YE 3 NAYE FIELD ADD KAR DE DELIVERY BOY KE LIYE
    role: { 
        type: String, 
        enum: ['area-manager', 'delivery-manager'], // area-manager ya delivery-manager
        default: 'area-manager' 
    },
    parentManager: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Manager' // kis area manager ne banaya
    },
    vehicleType: { 
        type: String, 
        enum: ['bike', 'cycle', 'auto', 'foot'], 
        default: 'bike' 
    }

}, {
    timestamps: true
});

module.exports = mongoose.model('Manager', managerSchema);