const mongoose = require('mongoose');

const managerSchema = new mongoose.Schema({
    areaCode: { type: String, required: true },
    managerCode: { type: String, required: true, unique: true },
    name: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String },
    city: { type: String },
    areaName: { type: String },
    bucket: { type: String, default: 'DEFAULT' },
    loginToken: { type: String, required: true },
    status: { type: Boolean, default: true },
    autoGenerated: { type: Boolean, default: true },
    serviceCharge: { type: Number, default: 0 },
    moduleAccess: [{ type: String }],
    centerLat: { type: Number },
    centerLng: { type: Number },
    radius: { type: Number },
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Manager', managerSchema);